### ISSUE TITLE
while importing experiment to an azure databricks, I am facing the following error

### ISSUE THREAD

**Issue by h-kloud006** [mlflow/mlflow-export-import#160]
FYI: I am copying experiments between azure databricks which are in different tenants

my command : import-experiment --experiment-name xxxxxxx --input-dir /tmp/export

MLflow Tracking URI: databricks
Options:
  input_dir: /tmp/export
  experiment_name: xxxxxx
  import_source_tags: False
  use_src_user_id: False
  dst_notebook_dir: None
in_databricks: False
importing_into_databricks: True
MLflowClient: databricks
Creating Databricks workspace directory ''
Traceback (most recent call last):
  File "c:\users\my-user\appdata\local\programs\python\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\my-user\appdata\local\programs\python\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\my-user\AppData\Local\Programs\Python\Python38\Scripts\import-experiment.exe\__main__.py", line 9, in <module>
  File "c:\users\my-user\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\my-user\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "c:\users\my-user\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\my-user\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\my-user\appdata\local\programs\python\python38\lib\site-packages\mlflow_export_import\experiment\import_experiment.py", line 94, in main
    importer.import_experiment(experiment_name, input_dir, dst_notebook_dir)
  File "c:\users\my-user\appdata\local\programs\python\python38\lib\site-packages\mlflow_export_import\experiment\import_experiment.py", line 58, in import_experiment
    mlflow_utils.set_experiment(self.mlflow_client, self.dbx_client, exp_name, tags)
  File "c:\users\my-user\appdata\local\programs\python\python38\lib\site-packages\mlflow_export_import\common\mlflow_utils.py", line 47, in set_experiment
    create_workspace_dir(dbx_client, os.path.dirname(exp_name))
  File "c:\users\my-user\appdata\local\programs\python\python38\lib\site-packages\mlflow_export_import\common\mlflow_utils.py", line 93, in create_workspace_dir
    dbx_client.post("workspace/mkdirs", { "path": workspace_dir })
  File "c:\users\my-user\appdata\local\programs\python\python38\lib\site-packages\mlflow_export_import\common\http_client.py", line 51, in post
    return json.loads(self._post(resource, data).text)
  File "c:\users\my-user\appdata\local\programs\python\python38\lib\site-packages\mlflow_export_import\common\http_client.py", line 47, in _post
    self._check_response(rsp, uri, data)
  File "c:\users\my-user\appdata\local\programs\python\python38\lib\site-packages\mlflow_export_import\common\http_client.py", line 64, in _check_response
    raise MlflowExportImportException(f"HTTP status code: {rsp.status_code}. Reason: {rsp.reason}. URI: {uri}. Params: {params}.")
mlflow_export_import.common.MlflowExportImportException: HTTP status code: 400. Reason: Bad Request. URI: https://adb-xxxxxxxx.x.azuredatabricks.net/api/2.0/workspace/mkdirs. Params: {"path": ""}.

**Comment by amesar** [comment]
> experiment_name: xxxxxx

You need specify a legal workspace path as the experiment name.
