### ISSUE TITLE
 Object of type MlflowExportImportException is not JSON serializable

### ISSUE THREAD

**Issue by EdgarTTRRL** [mlflow/mlflow-export-import#37]
When running import-all --input-dir <my_directory>

Traceback (most recent call last):
  File "/databricks/python3/bin/import-all", line 8, in <module>
    sys.exit(main())
  File "/databricks/python3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/databricks/python3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/databricks/python3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/databricks/python3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/databricks/python3/lib/python3.8/site-packages/mlflow_export_import/bulk/import_models.py", line 117, in main
    import_all(
  File "/databricks/python3/lib/python3.8/site-packages/mlflow_export_import/bulk/import_models.py", line 76, in import_all
    utils.write_json_file(fs, "import_report.json", dct)
  File "/databricks/python3/lib/python3.8/site-packages/mlflow_export_import/utils.py", line 78, in write_json_file
    fs.write(path, json.dumps(dct,indent=2)+"\n")
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MlflowExportImportException is not JSON serializable

**Comment by amesar** [comment]
@EdgarTTRRL I've fixed the issue and published a new PyPI version.
